// Action Type
export const ActionTypes = {
  GET_PRODUCTS_REQUEST: 'GET_PRODUCTS_REQUEST',
  GET_PRODUCTS_SUCCESS: 'GET_PRODUCTS_SUCCESS',
  GET_PRODUCTS_FAIL: 'GET_PRODUCTS_FAIL',

  GET_PRODUCT_DETAILS_REQUEST: 'GET_PRODUCT_DETAILS_REQUEST',
  GET_PRODUCT_DETAILS_SUCCESS: 'GET_PRODUCT_DETAILS_SUCCESS',
  GET_PRODUCT_DETAILS_FAIL: 'GET_PRODUCT_DETAILS_FAIL',
  GET_PRODUCT_DETAILS_RESET: 'GET_PRODUCT_DETAILS_RESET', 

  GET_SELECTED_PRODUCT_REQUEST: 'GET_SELECTED_PRODUCT_REQUEST',
  GET_SELECTED_PRODUCT_SUCCESS: 'GET_SELECTED_PRODUCT_SUCCESS',
  GET_SELECTED_PRODUCT_FAIL: 'GET_SELECTED_PRODUCT_FAIL',

  SET_PRODUCTS: 'SET_PRODUCTS',
  SELECTED_PRODUCT: 'SELECTED_PRODUCT',
  REMOVE_SELECTED_PRODUCT: 'REMOVE_SELECTED_PRODUCT',

  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CAR',
  CART_RESET: 'CART_RESET',
}